version: "3"

services:
  web:
      container_name : homeapp
      restart: always
      build: .
      ports: 
            - "3000:3000"
      volumes:
            - .:/usr/src/app
      environment:
            - VIRTUAL_HOST=homeapp.marlonfalcon.com
